# .github/workflows/gated_workflow.yml
name: Gated CI/CD Pipeline

on:
  push:
    branches: ["**"]

jobs:
  test-and-build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest test_app.py -v

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./k8s-demo/
          push: true
          tags: |
            ghcr.io/mcintoshd-ara/bcis309:latest
            ghcr.io/mcintoshd-ara/bcis309:${{ github.sha }}

      - name: Apply manifests
        run: |
          kubectl apply -f k8s-demo/k8s/dev/namespace.yaml
          kubectl apply -f k8s-demo/k8s/dev/deployment.yaml
          kubectl apply -f k8s-demo/k8s/dev/service.yaml

      - name: Update image to latest commit
        run: |
          kubectl set image deployment/k8s-demo \
            k8s-demo=ghcr.io/mcintoshd-ara/bcis309:${{ github.sha }} \
            -n dev
          kubectl rollout status deployment/k8s-demo -n dev --timeout=60s
  deploy-prod:
    runs-on: self-hosted
    needs: test-and-build
    environment: production
    steps:
      - name: Deploy to prod
        run: |
          kubectl set image deployment/k8s-demo \
            k8s-demo=ghcr.io/mcintoshd-ara/bcis309:${{ github.sha }} \
            -n prod
          kubectl rollout status deployment/k8s-demo -n prod --timeout=60s
